# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-18 00:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u56fe\u4e66\u540d\u79f0')),
                ('wirter', models.CharField(max_length=50, verbose_name='\u4f5c\u8005')),
                ('price', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='\u5546\u54c1\u5355\u4ef7')),
                ('inlibrary_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('max_acount', models.IntegerField(default=0, verbose_name='\u603b\u6570\u91cf')),
                ('now_acount', models.IntegerField(default=0, verbose_name='\u73b0\u6570\u91cf')),
                ('press', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.Supplier', verbose_name='\u4f9b\u5e94\u5546')),
            ],
            options={
                'verbose_name': '\u4e66\u7c4d\u4fe1\u606f',
                'verbose_name_plural': '\u4e66\u7c4d\u4fe1\u606f',
            },
        ),
    ]
