# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-18 00:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='\u5546\u54c1\u540d\u79f0')),
                ('count', models.IntegerField(default=0, verbose_name='\u5546\u54c1\u6570\u91cf')),
                ('price', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='\u5546\u54c1\u5355\u4ef7')),
                ('max_count', models.IntegerField(blank=True, null=True, verbose_name='\u5e93\u5b58\u4e0a\u9650')),
                ('min_count', models.IntegerField(default=0, verbose_name='\u5e93\u5b58\u4e0b\u9650')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.Supplier', verbose_name='\u4f9b\u5e94\u5546')),
            ],
            options={
                'verbose_name': '\u5546\u54c1',
                'verbose_name_plural': '\u5546\u54c1',
            },
        ),
    ]
