# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-18 21:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_store_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('count', models.IntegerField(default=0, verbose_name='\u5165\u5e93\u603b\u91cf')),
                ('en_store_type', models.IntegerField(choices=[(1, '\u6b63\u5e38\u5165\u5e93'), (2, '\u9000\u8d27\u5165\u5e93'), (3, '\u7269\u8d44\u8c03\u52a8')], default=1, verbose_name='\u5165\u5e93\u7c7b\u578b')),
            ],
            options={
                'verbose_name': '\u5165\u5e93\u8bb0\u5f55',
                'verbose_name_plural': '\u5165\u5e93\u8bb0\u5f55',
            },
        ),
        migrations.CreateModel(
            name='OutStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('out_store_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('count', models.IntegerField(default=0, verbose_name='\u51fa\u5e93\u603b\u91cf')),
                ('out_store_type', models.IntegerField(choices=[(1, '\u751f\u4ea7\u9886\u6599'), (2, '\u9500\u552e\u63d0\u8d27'), (3, '\u7269\u8d44\u8c03\u52a8')], default=1, verbose_name='\u51fa\u5e93\u7c7b\u578b')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Book', verbose_name='\u4e66\u7c4d')),
            ],
            options={
                'verbose_name': '\u51fa\u5e93\u8bb0\u5f55',
                'verbose_name_plural': '\u51fa\u5e93\u8bb0\u5f55',
            },
        ),
    ]
