# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-18 21:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operation', '0001_initial'),
        ('book', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('press', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outstore',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u804c\u5de5'),
        ),
        migrations.AddField(
            model_name='enstore',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Book', verbose_name='\u4e66\u7c4d'),
        ),
        migrations.AddField(
            model_name='enstore',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u804c\u5de5'),
        ),
        migrations.AddField(
            model_name='enstore',
            name='press',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='press.Press', verbose_name='\u51fa\u7248\u793e'),
        ),
    ]
