# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-18 21:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u5ba2\u6237\u540d\u79f0')),
                ('phone', models.CharField(max_length=15, verbose_name='\u8054\u7cfb\u7535\u8bdd')),
                ('address', models.CharField(max_length=100, verbose_name='\u5ba2\u6237\u5730\u5740')),
                ('contact', models.CharField(max_length=20, verbose_name='\u8054\u7cfb\u4eba')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u5ba2\u6237',
                'verbose_name_plural': '\u5ba2\u6237',
            },
        ),
    ]
