# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-18 00:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proof',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u501f\u9605\u8005\u540d\u79f0')),
                ('sex', models.IntegerField(choices=[(1, '\u7537'), (2, '\u5973')], default=1, verbose_name='\u6027\u522b')),
                ('birthday', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u751f\u65e5')),
                ('address', models.CharField(max_length=100, verbose_name='\u5ba2\u6237\u5730\u5740')),
                ('id_number', models.CharField(max_length=50, verbose_name='ID\u53f7\u7801')),
                ('phone', models.CharField(max_length=15, verbose_name='\u8054\u7cfb\u7535\u8bdd')),
                ('now_borrow_amount', models.IntegerField(default=0, verbose_name='\u501f\u9605\u6570')),
            ],
            options={
                'verbose_name': '\u501f\u9605\u8005',
                'verbose_name_plural': '\u501f\u9605\u8005',
            },
        ),
    ]
