# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-18 21:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proof', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proof',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='\u521b\u5efa\u65e5\u671f'),
        ),
    ]
